export _ESC_=$'\033'

export BLACK="${_ESC_}[0;30m"
export BLUE="${_ESC_}[0;34m"
export BROWN="${_ESC_}[0;33m"
export CYAN="${_ESC_}[0;36m"
export GREEN="${_ESC_}[0;32m"
export GREY="${_ESC_}[1;30m"
export PURPLE="${_ESC_}[0;35m"
export RED="${_ESC_}[0;31m"
export WHITE="${_ESC_}[1;37m"
export YELLOW="${_ESC_}[1;33m"
export LBROWN="${_ESC_}[1;33m"
export LBLUE="${_ESC_}[1;34m"
export LCYAN="${_ESC_}[1;36m"
export LGREY="${_ESC_}[0;37m"
export LGREEN="${_ESC_}[1;32m"
export LPURPLE="${_ESC_}[1;35m"
export LRED="${_ESC_}[1;31m"

export EMPH_HIGH="${_ESC_}[1m"
export EMPH_LOW="${_ESC_}[2m"
export EMPH_REG="${_ESC_}[22m"

export UND_ON="${_ESC_}[4m"
export UND_OFF="${_ESC_}[24m"

export ITAL_ON="${_ESC_}[3m"
export ITAL_OFF="${_ESC_}[23m"

export INV_ON="${_ESC_}[7m"
export INV_OFF="${_ESC_}[27m"

export BG_BLACK="${_ESC_}[0;40m"
export BG_BLUE="${_ESC_}[0;44m"
export BG_BROWN="${_ESC_}[0;43m"
export BG_CYAN="${_ESC_}[0;46m"
export BG_GREEN="${_ESC_}[0;42m"
export BG_GREY="${_ESC_}[1;40m"
export BG_PURPLE="${_ESC_}[0;45m"
export BG_RED="${_ESC_}[0;41m"
export BG_WHITE="${_ESC_}[1;47m"
export BG_YELLOW="${_ESC_}[1;43m"
export BG_LBROWN="${_ESC_}[1;43m"
export BG_LBLUE="${_ESC_}[1;44m"
export BG_LCYAN="${_ESC_}[1;46m"
export BG_LGREY="${_ESC_}[0;47m"
export BG_LGREEN="${_ESC_}[1;42m"
export BG_LPURPLE="${_ESC_}[1;45m"
export BG_LRED="${_ESC_}[1;41m"

export _NC_="${_ESC_}[0m"

